import type { SankeyData } from "./store"

export const sampleDatasets: Record<string, SankeyData> = {
  energyFlow: {
    name: "Energy Flow Example",
    nodes: [
      { name: "Agricultural 'waste'", color: "#5470c6" },
      { name: "Bio-conversion", color: "#91cc75" },
      { name: "Liquid", color: "#fac858" },
      { name: "Losses", color: "#ee6666" },
      { name: "Solid", color: "#73c0de" },
      { name: "Gas", color: "#3ba272" },
      { name: "Biofuel imports", color: "#fc8452" },
      { name: "Biomass imports", color: "#9a60b4" },
      { name: "Coal imports", color: "#ea7ccc" },
      { name: "Coal", color: "#5470c6" },
      { name: "Coal reserves", color: "#91cc75" },
      { name: "District heating", color: "#fac858" },
      { name: "Industry", color: "#ee6666" },
      { name: "Heating and cooling - commercial", color: "#73c0de" },
      { name: "Heating and cooling - homes", color: "#3ba272" },
      { name: "Electricity grid", color: "#fc8452" },
      { name: "Over generation / exports", color: "#9a60b4" },
      { name: "H2 conversion", color: "#ea7ccc" },
      { name: "Road transport", color: "#5470c6" },
      { name: "Agriculture", color: "#91cc75" },
      { name: "Rail transport", color: "#fac858" },
      { name: "Lighting & appliances - commercial", color: "#ee6666" },
      { name: "Lighting & appliances - homes", color: "#73c0de" },
      { name: "Gas imports", color: "#3ba272" },
      { name: "Ngas", color: "#fc8452" },
      { name: "Gas reserves", color: "#9a60b4" },
      { name: "Thermal generation", color: "#ea7ccc" },
      { name: "Geothermal", color: "#5470c6" },
      { name: "H2", color: "#91cc75" },
      { name: "Hydro", color: "#fac858" },
      { name: "International shipping", color: "#ee6666" },
      { name: "Domestic aviation", color: "#73c0de" },
      { name: "International aviation", color: "#3ba272" },
      { name: "National navigation", color: "#fc8452" },
      { name: "Marine algae", color: "#9a60b4" },
      { name: "Nuclear", color: "#ea7ccc" },
      { name: "Oil imports", color: "#5470c6" },
      { name: "Oil", color: "#91cc75" },
      { name: "Oil reserves", color: "#fac858" },
      { name: "Other waste", color: "#ee6666" },
      { name: "Pumped heat", color: "#73c0de" },
      { name: "Solar PV", color: "#3ba272" },
      { name: "Solar Thermal", color: "#fc8452" },
      { name: "Solar", color: "#9a60b4" },
      { name: "Tidal", color: "#ea7ccc" },
      { name: "UK land based bioenergy", color: "#5470c6" },
      { name: "Wave", color: "#91cc75" },
      { name: "Wind", color: "#fac858" },
    ],
    links: [
      { source: "Agricultural 'waste'", target: "Bio-conversion", value: 124.729 },
      { source: "Bio-conversion", target: "Liquid", value: 0.597 },
      { source: "Bio-conversion", target: "Losses", value: 26.862 },
      { source: "Bio-conversion", target: "Solid", value: 280.322 },
      { source: "Bio-conversion", target: "Gas", value: 81.144 },
      { source: "Biofuel imports", target: "Liquid", value: 35 },
      { source: "Biomass imports", target: "Solid", value: 35 },
      { source: "Coal imports", target: "Coal", value: 11.606 },
      { source: "Coal reserves", target: "Coal", value: 63.965 },
      { source: "Coal", target: "Solid", value: 75.571 },
      { source: "District heating", target: "Industry", value: 10.639 },
      { source: "District heating", target: "Heating and cooling - commercial", value: 22.505 },
      { source: "District heating", target: "Heating and cooling - homes", value: 46.184 },
      { source: "Electricity grid", target: "Over generation / exports", value: 104.453 },
      { source: "Electricity grid", target: "Heating and cooling - homes", value: 113.726 },
      { source: "Electricity grid", target: "H2 conversion", value: 27.14 },
      { source: "Electricity grid", target: "Industry", value: 342.165 },
      { source: "Electricity grid", target: "Road transport", value: 37.797 },
      { source: "Electricity grid", target: "Agriculture", value: 4.412 },
      { source: "Electricity grid", target: "Heating and cooling - commercial", value: 40.858 },
      { source: "Electricity grid", target: "Losses", value: 56.691 },
      { source: "Electricity grid", target: "Rail transport", value: 7.863 },
      { source: "Electricity grid", target: "Lighting & appliances - commercial", value: 90.008 },
      { source: "Electricity grid", target: "Lighting & appliances - homes", value: 93.494 },
      { source: "Gas imports", target: "Ngas", value: 40.719 },
      { source: "Gas reserves", target: "Ngas", value: 82.233 },
      { source: "Gas", target: "Heating and cooling - commercial", value: 0.129 },
      { source: "Gas", target: "Losses", value: 1.401 },
      { source: "Gas", target: "Thermal generation", value: 151.891 },
      { source: "Gas", target: "Agriculture", value: 2.096 },
      { source: "Gas", target: "Industry", value: 48.58 },
      { source: "Geothermal", target: "Electricity grid", value: 7.013 },
      { source: "H2 conversion", target: "H2", value: 20.897 },
      { source: "H2 conversion", target: "Losses", value: 6.242 },
      { source: "H2", target: "Road transport", value: 20.897 },
      { source: "Hydro", target: "Electricity grid", value: 6.995 },
      { source: "Liquid", target: "Industry", value: 121.066 },
      { source: "Liquid", target: "International shipping", value: 128.69 },
      { source: "Liquid", target: "Road transport", value: 135.835 },
      { source: "Liquid", target: "Domestic aviation", value: 14.458 },
      { source: "Liquid", target: "International aviation", value: 206.267 },
      { source: "Liquid", target: "Agriculture", value: 3.64 },
      { source: "Liquid", target: "National navigation", value: 33.218 },
      { source: "Liquid", target: "Rail transport", value: 4.413 },
      { source: "Marine algae", target: "Bio-conversion", value: 4.375 },
      { source: "Ngas", target: "Gas", value: 122.952 },
      { source: "Nuclear", target: "Thermal generation", value: 839.978 },
      { source: "Oil imports", target: "Oil", value: 504.287 },
      { source: "Oil reserves", target: "Oil", value: 107.703 },
      { source: "Oil", target: "Liquid", value: 611.99 },
      { source: "Other waste", target: "Solid", value: 56.587 },
      { source: "Other waste", target: "Bio-conversion", value: 77.81 },
      { source: "Pumped heat", target: "Heating and cooling - homes", value: 193.026 },
      { source: "Pumped heat", target: "Heating and cooling - commercial", value: 70.672 },
      { source: "Solar PV", target: "Electricity grid", value: 59.901 },
      { source: "Solar Thermal", target: "Heating and cooling - homes", value: 19.263 },
      { source: "Solar", target: "Solar Thermal", value: 19.263 },
      { source: "Solar", target: "Solar PV", value: 59.901 },
      { source: "Solid", target: "Agriculture", value: 0.882 },
      { source: "Solid", target: "Thermal generation", value: 400.12 },
      { source: "Solid", target: "Industry", value: 46.477 },
      { source: "Thermal generation", target: "Electricity grid", value: 525.531 },
      { source: "Thermal generation", target: "Losses", value: 787.129 },
      { source: "Thermal generation", target: "District heating", value: 79.329 },
      { source: "Tidal", target: "Electricity grid", value: 9.452 },
      { source: "UK land based bioenergy", target: "Bio-conversion", value: 182.01 },
      { source: "Wave", target: "Electricity grid", value: 19.013 },
      { source: "Wind", target: "Electricity grid", value: 289.366 },
    ],
  },
  budgetFlow: {
    name: "Budget Allocation",
    nodes: [
      { name: "Revenue", color: "#5470c6" },
      { name: "Sales", color: "#91cc75" },
      { name: "Marketing", color: "#fac858" },
      { name: "Engineering", color: "#ee6666" },
      { name: "Customer Support", color: "#73c0de" },
      { name: "Administration", color: "#3ba272" },
      { name: "Salaries", color: "#fc8452" },
      { name: "Software", color: "#9a60b4" },
      { name: "Office Space", color: "#ea7ccc" },
      { name: "Equipment", color: "#5470c6" },
      { name: "Training", color: "#91cc75" },
      { name: "Travel", color: "#fac858" },
      { name: "Advertising", color: "#ee6666" },
      { name: "Events", color: "#73c0de" },
      { name: "Profit", color: "#3ba272" },
    ],
    links: [
      { source: "Revenue", target: "Sales", value: 500 },
      { source: "Revenue", target: "Marketing", value: 200 },
      { source: "Revenue", target: "Engineering", value: 300 },
      { source: "Revenue", target: "Customer Support", value: 100 },
      { source: "Revenue", target: "Administration", value: 150 },
      { source: "Revenue", target: "Profit", value: 250 },

      { source: "Sales", target: "Salaries", value: 300 },
      { source: "Sales", target: "Travel", value: 100 },
      { source: "Sales", target: "Software", value: 50 },
      { source: "Sales", target: "Training", value: 50 },

      { source: "Marketing", target: "Salaries", value: 80 },
      { source: "Marketing", target: "Advertising", value: 80 },
      { source: "Marketing", target: "Events", value: 40 },

      { source: "Engineering", target: "Salaries", value: 200 },
      { source: "Engineering", target: "Software", value: 50 },
      { source: "Engineering", target: "Equipment", value: 30 },
      { source: "Engineering", target: "Training", value: 20 },

      { source: "Customer Support", target: "Salaries", value: 70 },
      { source: "Customer Support", target: "Software", value: 20 },
      { source: "Customer Support", target: "Training", value: 10 },

      { source: "Administration", target: "Salaries", value: 80 },
      { source: "Administration", target: "Office Space", value: 50 },
      { source: "Administration", target: "Equipment", value: 20 },
    ],
  },
  migrationFlow: {
    name: "Population Migration",
    nodes: [
      { name: "North America", color: "#5470c6" },
      { name: "South America", color: "#91cc75" },
      { name: "Europe", color: "#fac858" },
      { name: "Africa", color: "#ee6666" },
      { name: "Asia", color: "#73c0de" },
      { name: "Oceania", color: "#3ba272" },
    ],
    links: [
      { source: "North America", target: "Europe", value: 5200 },
      { source: "North America", target: "Asia", value: 3800 },
      { source: "North America", target: "South America", value: 2700 },
      { source: "North America", target: "Oceania", value: 1500 },
      { source: "North America", target: "Africa", value: 800 },

      { source: "South America", target: "North America", value: 4800 },
      { source: "South America", target: "Europe", value: 3200 },
      { source: "South America", target: "Asia", value: 1200 },
      { source: "South America", target: "Africa", value: 600 },
      { source: "South America", target: "Oceania", value: 400 },

      { source: "Europe", target: "North America", value: 4100 },
      { source: "Europe", target: "Asia", value: 3700 },
      { source: "Europe", target: "Africa", value: 2500 },
      { source: "Europe", target: "South America", value: 1800 },
      { source: "Europe", target: "Oceania", value: 1200 },

      { source: "Africa", target: "Europe", value: 6200 },
      { source: "Africa", target: "Asia", value: 3100 },
      { source: "Africa", target: "North America", value: 2100 },
      { source: "Africa", target: "South America", value: 1100 },
      { source: "Africa", target: "Oceania", value: 500 },

      { source: "Asia", target: "North America", value: 5600 },
      { source: "Asia", target: "Europe", value: 4900 },
      { source: "Asia", target: "Oceania", value: 2800 },
      { source: "Asia", target: "Africa", value: 1900 },
      { source: "Asia", target: "South America", value: 900 },

      { source: "Oceania", target: "Asia", value: 2500 },
      { source: "Oceania", target: "North America", value: 1600 },
      { source: "Oceania", target: "Europe", value: 1400 },
      { source: "Oceania", target: "South America", value: 400 },
      { source: "Oceania", target: "Africa", value: 300 },
    ],
  },
}
